### ISSUE TITLE
ImportError: cannot import name 'swin_transformer' from 'Models' 

### ISSUE THREAD

**Issue by yjlam** [GTLIDAR/DeformableObjectsGrasping#2]
Hi,

Thanks for building up such an amazing code and making it open-sourced!

I met a problem during running the training demo for slip detection. I have a quick check on the Model module and can't find any swim_transformer at all. 

Could you please give me some suggestions?

```
Traceback (most recent call last):
  File "main_cluster.py", line 1, in <module>
    from train import train_net
  File "/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/train.py", line 17, in <module>
    from utils import model_factory
  File "/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/utils/model_factory.py", line 5, in <module>
    from Models import swin_transformer, vivit,vivit_two ,vivit_FDP, vivit_FDP_two, basic_CNN, swin_transformer_two, timeSformer_orig, timeSformer_orig_two
ImportError: cannot import name 'swin_transformer' from 'Models' (/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/Models/__init__.py)
```
All the best,

**Comment by yjlam** [comment]
I just deleted the missing models.
