### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dantian123121** [GTLIDAR/DeformableObjectsGrasping#4]
I had this problem：ImportError: cannot import name 'swin_transformer' from 'Models' (D:\Anaconda\ruanjian\Notebook\DeformableObjectsGrasping-master\DeformableObjectsGrasping-master\src\slip_detection\Models\__init__.py).I want to know which pre-training data sets need to be downloaded.

**Comment by Viva176** [comment]
你也在复现这篇吗，可以加个好友交流一下吗。vx Viva__1004

**Comment by y8han** [comment]
Swin_transformer was not included in the final version of the released codes. We only provides with the implementation codes for Timesformer and Vivit.

**Comment by y8han** [comment]
You can refer to the solution here: https://github.com/GTLIDAR/DeformableObjectsGrasping/issues/2#issuecomment-1143485248.

**Comment by serendipityrain** [comment]
> 你好，
> 
> 感谢您构建如此出色的代码并将其开源！
> 
> 我在运行滑动检测训练演示时遇到了问题。我快速检查了模型模块，但根本找不到任何 swim_transformer。
> 
> 你能给我一些建议吗？
> 
> ```
> Traceback (most recent call last):
>   File "main_cluster.py", line 1, in <module>
>     from train import train_net
>   File "/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/train.py", line 17, in <module>
>     from utils import model_factory
>   File "/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/utils/model_factory.py", line 5, in <module>
>     from Models import swin_transformer, vivit,vivit_two ,vivit_FDP, vivit_FDP_two, basic_CNN, swin_transformer_two, timeSformer_orig, timeSformer_orig_two
> ImportError: cannot import name 'swin_transformer' from 'Models' (/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/Models/__init__.py)
> ```
> 
> 一切顺利，



> 你也在复现这篇文章吗，可以加个好朋友交流一下吗。vx Viva__1004

您好，请问您复现出这篇文章了吗，可以交流一下吗。

**Comment by PluteW** [comment]
> > 你好，
> > 感谢您构建如此出色的代码并将其开源！
> > 我在运行滑动检测训练演示时遇到了问题。我快速检查了模型模块，但根本找不到任何 swim_transformer。
> > 你能给我一些建议吗？
> > ```
> > Traceback (most recent call last):
> >   File "main_cluster.py", line 1, in <module>
> >     from train import train_net
> >   File "/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/train.py", line 17, in <module>
> >     from utils import model_factory
> >   File "/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/utils/model_factory.py", line 5, in <module>
> >     from Models import swin_transformer, vivit,vivit_two ,vivit_FDP, vivit_FDP_two, basic_CNN, swin_transformer_two, timeSformer_orig, timeSformer_orig_two
> > ImportError: cannot import name 'swin_transformer' from 'Models' (/home/bourne/slip_detection/DeformableObjectsGrasping/src/slip_detection/Models/__init__.py)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 一切顺利，
> 
> > 你也在复现这篇文章吗，可以加个好朋友交流一下吗。vx Viva__1004
> 
> 您好，请问您复现出这篇文章了吗，可以交流一下吗。

您好，请问复现进展如何，可以交流下么。vx：VirJinl
